version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "DAew0907!0515"
      MYSQL_DATABASE: "MKBoardDB"
      MYSQL_USER: "chu"
      MYSQL_PASSWORD: "DAew0907!0515"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  apache2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/mk-board
    depends_on:
      - mysql
    hostname: mk-board-apache2

volumes:
  mysql-data:
