version: '3'

services:
  mysql:
    image: mysql:latest
    env_file:
      - ./dockerConf.ini
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  apache2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8060:80"
    volumes:
      - ./:/var/www/html/mk-board
    depends_on:
      - mysql
    hostname: mk-board-apache2

volumes:
  mysql-data:
